---
remote_theme: 'poole/hyde'
title: Software Engineering Manager
base_url: '/resume/'
plugins: [jekyll-paginate]

author:
  name: 'Andrew Barrows'
  url: https://andybarrows.com

# Dependencies
email: andy@andybarrows.com
github_username: abarrows

# Markdown
kramdown:
  input: GFM # GitHub Flavored Markdown
  hard_wrap: false

# Permalinks
permalink: pretty

# Setup
tagline: 'Software Engineering Manager'
description: 'This repo serves as a single source of truth for my resume and related information.'
url: https://github.com/abarrows/resume

defaults:
  - scope:
      path: 'formats'
    values:
      layout: 'default'

paginate: 5

# Custom vars
github:
  repo: https://github.com/abarrows/resume
