name: Publish Resume Formats

on:
  workflow_dispatch:
  push:
    # paths:
    #   - 'positions/index.md'
  release:
    types: [published]

env:
  resume_path: 'positions'
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish-formats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown2 pypandoc

      - name: Convert Markdown to HTML
        run: |
          python -c "import markdown2; html = markdown2.markdown_path('${{env.resume_path}}/index.md'); open('${{env.resume_path}}/resume.html', 'w').write(html)"

      - name: Convert Markdown to PDF
        run: |
          pandoc ${{env.resume_path}}/resume.md -o ${{env.resume_path}}/resume.pdf

      - name: Generate JSON version of Resume
        run: |
          python -c "import json; md = open('${{env.resume_path}}/index.md').read(); json.dump({'content': md}, open('${{env.resume_path}}/index.json', 'w'))"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Resume-Formats
          path: positions/

      - name: 'Upload Resume and Formats'
        uses: actions/upload-artifact@v4
        with:
          name: resume-formats
          path: |
            ${{ env.resume_path }}
            ${{ env.resume_path }}/formats/
