name: Publish Resume Formats

on:
  workflow_dispatch:
  push:
    # paths:
    #   - './index.md'
  release:
    types: [published]

env:
  resume_path: './'
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish-formats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown2

      # - name: Convert Markdown to HTML
      #   run: |
      #     python -c "import markdown2; html = markdown2.markdown_path('${{env.resume_path}}/index.md'); open('${{env.resume_path}}/index.html', 'w').write(html)"

      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=${{env.resume_path}}index.pdf ${{env.resume_path}}index.md

      - name: 'Generate JSON version of Resume'
        run: |
          python -c "import json; md = open('${{env.resume_path}}index.md').read(); json.dump({'content': md}, open('${{env.resume_path}}index.json', 'w'))"

      # - name: 'Upload Resume and Formats'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: resume-formats
      #     path: |
      #       ${{ env.resume_path }}index.md
      #       ${{ env.resume_path }}formats/index.json
      #       ${{ env.resume_path }}formats/index.pdf
      - name: 'Commit Resume in Various Formats'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Adding pdf, json, markdown, and html versions of resume'
